spring.application.name=product-service
server.port=9093
spring.mongodb.uri=mongodb+srv://shahani200515_db_user:XkAxlMfgHBQgCRRy@product-service.rzlxt6y.mongodb.net/product-service

#logging.level.org.springframework.data.mongodb=DEBUG